# mongo-sharding-repl-cache
services:
  # mongo
  #  сервер конфигурации mongo
  configSrv:
    image: mongo:latest
    container_name: configSrv
    restart: always
    ports:
      - "27017:27017"
    networks:
      app-network:
        ipv4_address: 173.17.0.10
    volumes:
      - mongo-config-db:/data/db
      - mongo-config-configdb:/data/configdb
    command:
      [
        "--configsvr",  # запуск в режиме конфигурации
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27017" ,"--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  #  1-й шард
  shard1-a:
    image: mongo:latest
    container_name: shard1-a
    restart: always
    ports:
      - "27018:27018"
    networks:
      app-network:
        ipv4_address: 173.17.1.1
    volumes:
      - mongo-shard1-a-data:/data/db
    command:
      [
        "--shardsvr", # запуск в режиме шардинга
        "--replSet",
        "rs-shard1", # название реплики
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27018" ,"--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1-b:
    image: mongo:latest
    container_name: shard1-b
    restart: always
    ports:
      - "27118:27018"
    networks:
      app-network:
        ipv4_address: 173.17.1.2
    volumes:
      - mongo-shard1-b-data:/data/db
    command:
      [
        "--shardsvr", # запуск в режиме шардинга
        "--replSet",
        "rs-shard1", # название реплики
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27018" ,"--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1-c:
    image: mongo:latest
    container_name: shard1-c
    restart: always
    ports:
      - "27218:27018"
    networks:
      app-network:
        ipv4_address: 173.17.1.3
    volumes:
      - mongo-shard1-c-data:/data/db
    command:
      [
        "--shardsvr", # запуск в режиме шардинга
        "--replSet",
        "rs-shard1", # название реплики
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27018" ,"--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  #  2-й шард
  shard2-a:
    image: mongo:latest
    container_name: shard2-a
    restart: always
    ports:
      - "27019:27019"
    networks:
      app-network:
        ipv4_address: 173.17.2.1
    volumes:
      - mongo-shard2-a-data:/data/db
    command:
      [
        "--shardsvr", # запуск в режиме шардинга
        "--replSet",
        "rs-shard2", # название реплик
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27019" ,"--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2-b:
    image: mongo:latest
    container_name: shard2-b
    restart: always
    ports:
      - "27119:27019"
    networks:
      app-network:
        ipv4_address: 173.17.2.2
    volumes:
      - mongo-shard2-b-data:/data/db
    command:
      [
        "--shardsvr", # запуск в режиме шардинга
        "--replSet",
        "rs-shard2", # название реплик
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27019" ,"--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2-c:
    image: mongo:latest
    container_name: shard2-c
    restart: always
    ports:
      - "27219:27019"
    networks:
      app-network:
        ipv4_address: 173.17.2.3
    volumes:
      - mongo-shard2-c-data:/data/db
    command:
      [
        "--shardsvr", # запуск в режиме шардинга
        "--replSet",
        "rs-shard2", # название реплик
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27019" ,"--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  #  роутер mongo
  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - "27020:27020"
    networks:
      app-network:
        ipv4_address: 173.17.0.7
    command:
      [
        "mongos", # обычная mongo в режиме роутера
        "--configdb",
        "config_server/configSrv:27017", # передача данных сервера конфигурации
        "--bind_ip_all",
        "--port",
        "27020"
      ]
    healthcheck:
      test: [ "CMD", "mongosh","--port", "27020", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  # redis
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis/redis_standalone.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      app-network:
        ipv4_address: 173.17.3.1

  # app
  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    networks:
      app-network:
        ipv4_address: 173.17.0.6
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router:27020"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis:6379"

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16

volumes:
  # mongo
  mongo-config-db:
  mongo-config-configdb:
  mongo-shard1-a-data:
  mongo-shard1-b-data:
  mongo-shard1-c-data:
  mongo-shard2-a-data:
  mongo-shard2-b-data:
  mongo-shard2-c-data:
  # redis
  redis_data: {}